version: '3.6'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  mysql_core_db:
    build: mysql
    container_name: mysql_javatodev_app
    environment:
      MYSQL_ROOT_PASSWORD: woVERANKliGharym
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

  internet-banking-config-server:
    image: javatodev/internet-banking-config-server
    ports:
      - 8090:8090

  internet-banking-service-registry:
    image: javatodev/internet-banking-service-registry
    ports:
      - 8081:8081

volumes:
  postgres_data:
  mysqldata: