server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

logging:
  file:
    name: '/var/log/internet-banking-service-registry/application.log'
