name: CI For Concept Microservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, version-upgrade ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [
        'core-banking-service', 
        'internet-banking-fund-transfer-service', 
        'internet-banking-user-service', 
        'internet-banking-utility-payment-service',
        'internet-banking-service-registry',
        'internet-banking-api-gateway'
        ] }
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0   

    - name: Build
      run: ./gradlew build -x test
      working-directory: ${{ matrix.dir }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: microservice-artifacts
        path: |
          core-banking-service/build/libs/core-banking-service-0.0.1-SNAPSHOT.jar
          internet-banking-api-gateway/build/libs/internet-banking-api-gateway-0.0.1-SNAPSHOT.jar
        retention-days: 1
        overwrite: true
        
